using TravelCheck.Application.Interfaces;
using TravelCheck.Application.Dtos;
using TravelCheck.Domain.Entities;
using TravelCheck.Domain.Enums;
using TravelCheck.Application.Events;
using System.Text.Json;
using System.Diagnostics;

namespace TravelCheck.Application.Services;

public class TripService
{
    private readonly ITripRepository _repository;
    private readonly IOutboxRepository _outboxRepository;

    public TripService(ITripRepository repository, IOutboxRepository outboxRepository)
    {
        _repository = repository;
        _outboxRepository = outboxRepository;
    }

    // CREATE → TripCreatedEvent
    public async Task<Guid> CreateAsync(CreateTripDto dto)
    {
        var trip = new Trip(dto.EmployeeName, dto.Country, dto.From, dto.To);

        await _repository.AddAsync(trip);

        await AddToOutboxAsync(new TripCreatedEvent(trip.Id));

        return trip.Id;
    }

    // READ 
    public async Task<IEnumerable<Trip>> GetAllAsync()
    {
        return await _repository.GetAllAsync();
    }

    public async Task<Trip?> GetByIdAsync(Guid id)
    {
        return await _repository.GetByIdAsync(id);
    }

    // UPDATE → TripUpdatedEvent
    public async Task<Trip> UpdateAsync(Guid id, UpdateTripDto dto)
    {
        var trip = await _repository.GetByIdAsync(id);

        if (trip == null)
            throw new Exception("trip not found");

        trip.UpdateDetails(dto.EmployeeName, dto.Country, dto.From, dto.To);

        await _repository.UpdateAsync(trip);

        await AddToOutboxAsync(new TripUpdatedEvent(trip.Id));

        return trip;
    }

    // DELETE → TripDeletedEvent
    public async Task<Trip> DeleteAsync(Guid id)
    {
        var trip = await _repository.GetByIdAsync(id);

        if (trip == null)
            throw new Exception("trip not found");

        await _repository.DeleteAsync(id);

        await AddToOutboxAsync(new TripDeletedEvent(id));

        return trip;
    }

    // STATUS CHANGE → TripStatusChangedEvent (for WORKER - consumer only)
    public async Task<Trip> ChangeStatusAsync(Guid id, TripStatus newStatus)
    {
        var trip = await _repository.GetByIdAsync(id);

        if (trip == null)
            throw new Exception("trip not found");

        trip.ChangeStatus(newStatus);

        await _repository.UpdateAsync(trip);

        await AddToOutboxAsync(
            new TripStatusChangedEvent(trip.Id, newStatus)
        );

        return trip;
    }

    // OUTBOX HELPER
    private Task AddToOutboxAsync<TEvent>(TEvent evt)
    {
        var type = evt!.GetType().Name;
        var activity = Activity.Current;

        var outbox = new OutboxEvent
        {
            Id = Guid.NewGuid(),
            Type = type, // partition key
            Payload = JsonSerializer.Serialize(evt),
            OccurredAt = DateTimeOffset.UtcNow,
            Processed = false,

            // activity.(...) datas are generated by asp.net
            CorrelationId = activity?.TraceId.ToString(),
            TraceParent = activity?.Id,
            TraceState = activity?.TraceStateString
        };

        return _outboxRepository.AddAsync(outbox);
    }
}
