using System.Diagnostics;
using System.Text.Json;
using TravelCheck.Application.Interfaces;
using TravelCheck.Domain.Entities;

namespace TravelCheck.Application.Outbox;
public sealed class OutboxEventPublisher : IOutboxEventPublisher
{
    private readonly IOutboxRepository _outboxRepository;

    public OutboxEventPublisher(IOutboxRepository outboxRepository)
    {
        _outboxRepository = outboxRepository;
    }

    // OUTBOX HELPER
    public Task PublishAsync<TEvent>(TEvent evt, CancellationToken ct = default)
    {
        var type = evt!.GetType().Name;
        var activity = Activity.Current;

        var outboxEvent = new OutboxEvent
        {
            Id = Guid.NewGuid(),
            Type = type, // partition key
            Payload = JsonSerializer.Serialize(evt),
            OccurredAt = DateTimeOffset.UtcNow,
            Processed = false,

            // Trace data (generated by ASP.NET / propagated via Activity)
            CorrelationId = activity?.TraceId.ToString(),
            TraceParent = activity?.Id,
            TraceState = activity?.TraceStateString
        };

        return _outboxRepository.AddAsync(outboxEvent, ct);
    }
}
